version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/app

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Build and Test
      # - run:
      #     name: Run Tests
      #     command: npm run test

      # Deployment to Vercel
      - run:
          name: Deploy to Vercel
          command: |
            npm install -g vercel
            vercel 

      
